# Generated by Django 4.2.2 on 2023-08-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='game_day',
        ),
        migrations.RemoveField(
            model_name='section',
            name='skill_level',
        ),
    ]
