# Generated by Django 4.2.2 on 2023-08-01 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_course_student_course_section_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.student'),
            preserve_default=False,
        ),
    ]
